### ISSUE TITLE
"_WidgetsInTempalteMixin" misspelling

### ISSUE THREAD

**Issue by gavinr** [dojo/dojo-website#12]
"_WidgetsInTemplateMixin" is misspelled to "_WidgetsInTempalteMixin" on the `_AttachMixin` documentation page:

https://github.com/dojo/dojo-website/search?utf8=%E2%9C%93&q=%22_WidgetsInTempalteMixin%22

**Comment by kfranqueiro** [comment]
FYI that originates from the dojo/docs repo, e.g. https://github.com/dojo/docs/blob/master/dijit/_AttachMixin.rst (and versions on 1.x branches), which is what the reference-guide pages get generated from.

**Comment by gavinr** [comment]
ah good to know. I'll close this and move over to that other repo. Thanks!
