### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by kborchers** [dojo/dojo-website#14]
A license needs to be stated and CLA signatures collected for contributions to this repo

**Comment by dylans** [comment]
@kborchers what do you recommend for the website repo? We weren't sure how to license it, as we don't really want to encourage someone to clone the Dojo website as is at the risk of confusion. So we hadn't made a decision on how to license it. It's a relatively step for us making the website repo public.

**Comment by kborchers** [comment]
You could do something similar to what we do for the jQuery sites like https://github.com/jquery/jquery.com/blob/master/LICENSE.txt. Use a similar format, use BSD instead of MIT if you prefer, then follow it up with an additional statement which you could adapt from what we use in jquery-wp-content:

> The design, layout, and look-and-feel of jquery-wp-content - including
all CSS, images, and icons, except as noted above - are copyright jQuery
Foundation and are not licensed for use. Designs and CSS from
jquery-wp-content may not be used on any site, personal or commerical,
without prior written consent from the jQuery Foundation.

> The only permitted (and encouraged) exception to "use" is the case of
cloning/forking this repository in order to create a local development
environment to facilitate making contributions to jQuery Foundation
web sites.

**Comment by JSFOwner** [comment]
Just wanted to ping this as a LICENSE file is necessary in every repo under the JSF CLA. Also, copyright statements in the footer of the site need to be updated as well as http://dojotoolkit.org/license.html

**Comment by kborchers** [comment]
Just wanted to ping this as a LICENSE file is necessary in every repo under the JSF CLA. Also, copyright statements in the footer of the site need to be updated as well as http://dojotoolkit.org/license.html

**Comment by dylans** [comment]
Thanks for the reminder, closed via #28.
