### ISSUE TITLE
dojotoolkit.org is down

### ISSUE THREAD

**Issue by TiBeN** [dojo/dojo-website#36]
Hi, 
Hosted website [dojotoolkit.org](https://dojotoolkit.org/) seems down.

**Comment by morrinene** [comment]
Hi @TiBeN [dojotoolkit.org](https://dojotoolkit.org/) is available again.  We had an issue with a DNS transfer that took it offline until late Tuesday last week. Please let me know if anything is not coming up for you and I'll look into it.

**Comment by TiBeN** [comment]
okay thanks. Works fine for me.
